[package]
name = "services"
edition.workspace = true
version.workspace = true

[dependencies]
domain.workspace = true
sea-orm.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true
anyhow.workspace = true
redis.workspace = true

thiserror = "2.0.20"
jsonwebtoken = { version = "11.0.0", features = ["rust_crypto"] }
argon2 = "0.6.0"
sha2 = "0.11.0"
sha1 = "0.11.0"
base64 = "0.23.1"
hex = "0.4.3"
time = "0.3.55"
reqwest = { version = "0.13.4", default-features = false, features = ["json", "rustls"] }
askama = "0.16.0"
rust-i18n = "4.2.1"
lettre = { version = "0.11.23", default-features = false, features = ["builder", "tokio1-rustls-tls", "smtp-transport"] }
chrono-tz = "0.10.4"
subtle = "2.6.1"
rand = "0.10.2"
