//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod allowed_emails_domains;
pub mod auth_tokens;
pub mod blocked_emails_domains;
pub mod instance_alerts;
pub mod instance_audit_logs;
pub mod refresh_tokens;
pub mod reserved_usernames;
pub mod user_emails;
pub mod users;
