//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::allowed_emails_domains::Entity as AllowedEmailsDomains;
pub use super::auth_tokens::Entity as AuthTokens;
pub use super::blocked_emails_domains::Entity as BlockedEmailsDomains;
pub use super::instance_alerts::Entity as InstanceAlerts;
pub use super::instance_audit_logs::Entity as InstanceAuditLogs;
pub use super::instance_settings::Entity as InstanceSettings;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::reserved_usernames::Entity as ReservedUsernames;
pub use super::user_emails::Entity as UserEmails;
pub use super::users::Entity as Users;
