//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    #[sea_orm(column_type = "custom(\"citext\")", save_as = "citext", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub first_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar_url: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub theme: String,
    #[sea_orm(column_type = "Text")]
    pub locale: String,
    pub is_instance_admin: bool,
    pub suspended_at: Option<DateTimeWithTimeZone>,
    pub suspended_until: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub suspended_reason: Option<String>,
    pub suspended_by: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub last_activity_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::allowed_emails_domains::Entity")]
    AllowedEmailsDomains,
    #[sea_orm(has_many = "super::auth_tokens::Entity")]
    AuthTokens,
    #[sea_orm(has_many = "super::blocked_emails_domains::Entity")]
    BlockedEmailsDomains,
    #[sea_orm(has_many = "super::instance_alerts::Entity")]
    InstanceAlerts,
    #[sea_orm(has_many = "super::refresh_tokens::Entity")]
    RefreshTokens,
    #[sea_orm(has_many = "super::reserved_usernames::Entity")]
    ReservedUsernames,
    #[sea_orm(has_many = "super::user_emails::Entity")]
    UserEmails,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::SuspendedBy",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SelfRef,
}

impl Related<super::allowed_emails_domains::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AllowedEmailsDomains.def()
    }
}

impl Related<super::auth_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthTokens.def()
    }
}

impl Related<super::blocked_emails_domains::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlockedEmailsDomains.def()
    }
}

impl Related<super::instance_alerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InstanceAlerts.def()
    }
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl Related<super::reserved_usernames::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReservedUsernames.def()
    }
}

impl Related<super::user_emails::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserEmails.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
